/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajout_produit (void);
GtkWidget* create_Afficher_produit (void);
GtkWidget* create_modifie_produit (void);
GtkWidget* create_supprimer_produit (void);
GtkWidget* create_employe (void);
GtkWidget* create_ajout_employe (void);
GtkWidget* create_Afficher_employe (void);
GtkWidget* create_accueil (void);
GtkWidget* create_admin (void);
GtkWidget* create_modifier_employe (void);
