/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajout_produit (void)
{
  GtkWidget *ajout_produit;
  GtkWidget *alignment22;
  GtkWidget *fixed1;
  GtkWidget *entryQuantite_Produit;
  GtkWidget *entryNom_Produit;
  GtkWidget *entryPrixunitaire_Produit;
  GtkObject *spinbutton_jourajoutproduit_adj;
  GtkWidget *spinbutton_jourajoutproduit;
  GtkObject *spinbutton_moisajoutproduit_adj;
  GtkWidget *spinbutton_moisajoutproduit;
  GtkObject *spinbutton_anneeajoutproduit_adj;
  GtkWidget *spinbutton_anneeajoutproduit;
  GtkWidget *image16;
  GtkWidget *Pr__c__dent_ajouter_afficher_produit;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label21;
  GtkWidget *ok;
  GtkWidget *image14;
  GtkWidget *label13;
  GtkWidget *labelannee;
  GtkWidget *labeljour;
  GtkWidget *labelmois;
  GtkWidget *labelnom_produit;
  GtkWidget *labeldate_produit;
  GtkWidget *labeltype_produit;
  GtkWidget *labelquantit___produit;
  GtkWidget *labelprix_produit;
  GtkWidget *Ajouter_Produit;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label7;
  GtkWidget *comboboxtypep;
  GtkWidget *labelerreurnom;
  GtkWidget *labelerreurquantite;
  GtkWidget *labelerreurprixunitaire;

  ajout_produit = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajout_produit, 624, 464);
  gtk_window_set_title (GTK_WINDOW (ajout_produit), _("ajout_produit"));
  gtk_window_set_position (GTK_WINDOW (ajout_produit), GTK_WIN_POS_CENTER);

  alignment22 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (ajout_produit), alignment22);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (alignment22), fixed1);
  gtk_widget_set_size_request (fixed1, 624, 464);

  entryQuantite_Produit = gtk_entry_new ();
  gtk_widget_show (entryQuantite_Produit);
  gtk_fixed_put (GTK_FIXED (fixed1), entryQuantite_Produit, 208, 272);
  gtk_widget_set_size_request (entryQuantite_Produit, 224, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryQuantite_Produit), 8226);

  entryNom_Produit = gtk_entry_new ();
  gtk_widget_show (entryNom_Produit);
  gtk_fixed_put (GTK_FIXED (fixed1), entryNom_Produit, 208, 56);
  gtk_widget_set_size_request (entryNom_Produit, 224, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNom_Produit), 8226);

  entryPrixunitaire_Produit = gtk_entry_new ();
  gtk_widget_show (entryPrixunitaire_Produit);
  gtk_fixed_put (GTK_FIXED (fixed1), entryPrixunitaire_Produit, 208, 336);
  gtk_widget_set_size_request (entryPrixunitaire_Produit, 224, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPrixunitaire_Produit), 8226);

  spinbutton_jourajoutproduit_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_jourajoutproduit = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_jourajoutproduit_adj), 1, 0);
  gtk_widget_show (spinbutton_jourajoutproduit);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton_jourajoutproduit, 280, 144);
  gtk_widget_set_size_request (spinbutton_jourajoutproduit, 72, 27);

  spinbutton_moisajoutproduit_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_moisajoutproduit = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_moisajoutproduit_adj), 1, 0);
  gtk_widget_show (spinbutton_moisajoutproduit);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton_moisajoutproduit, 280, 184);
  gtk_widget_set_size_request (spinbutton_moisajoutproduit, 72, 27);

  spinbutton_anneeajoutproduit_adj = gtk_adjustment_new (1, 2020, 2050, 1, 10, 10);
  spinbutton_anneeajoutproduit = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_anneeajoutproduit_adj), 1, 0);
  gtk_widget_show (spinbutton_anneeajoutproduit);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton_anneeajoutproduit, 280, 224);
  gtk_widget_set_size_request (spinbutton_anneeajoutproduit, 72, 27);

  image16 = create_pixmap (ajout_produit, "plat-isometrique-production-oeufs-ferme-intelligente_82574-6427.jpeg");
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed1), image16, 0, 0);
  gtk_widget_set_size_request (image16, 624, 464);

  Pr__c__dent_ajouter_afficher_produit = gtk_button_new ();
  gtk_widget_show (Pr__c__dent_ajouter_afficher_produit);
  gtk_fixed_put (GTK_FIXED (fixed1), Pr__c__dent_ajouter_afficher_produit, 32, 400);
  gtk_widget_set_size_request (Pr__c__dent_ajouter_afficher_produit, 104, 45);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (Pr__c__dent_ajouter_afficher_produit), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Pr\303\251c\303\251dent"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox7), label21, FALSE, FALSE, 0);

  ok = gtk_button_new ();
  gtk_widget_show (ok);
  gtk_fixed_put (GTK_FIXED (fixed1), ok, 456, 104);
  gtk_widget_set_size_request (ok, 32, 29);
  gtk_button_set_focus_on_click (GTK_BUTTON (ok), FALSE);

  image14 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_container_add (GTK_CONTAINER (ok), image14);

  label13 = gtk_label_new (_(" <span foreground=\"blue\"><b>veuillez remplir le formulaire</b></span>\n"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed1), label13, 184, 8);
  gtk_widget_set_size_request (label13, 288, 56);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  labelannee = gtk_label_new (_("<span foreground=\"black\"><b>ann\303\251e </b></span>"));
  gtk_widget_show (labelannee);
  gtk_fixed_put (GTK_FIXED (fixed1), labelannee, 216, 232);
  gtk_widget_set_size_request (labelannee, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelannee), TRUE);

  labeljour = gtk_label_new (_("<span foreground=\"black\"><b>jour</b> </span>"));
  gtk_widget_show (labeljour);
  gtk_fixed_put (GTK_FIXED (fixed1), labeljour, 224, 152);
  gtk_widget_set_size_request (labeljour, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (labeljour), TRUE);

  labelmois = gtk_label_new (_("<span foreground=\"black\"><b>mois </b></span>"));
  gtk_widget_show (labelmois);
  gtk_fixed_put (GTK_FIXED (fixed1), labelmois, 224, 192);
  gtk_widget_set_size_request (labelmois, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelmois), TRUE);

  labelnom_produit = gtk_label_new (_("<span foreground=\"black\"><b>nom</b></span>"));
  gtk_widget_show (labelnom_produit);
  gtk_fixed_put (GTK_FIXED (fixed1), labelnom_produit, 96, 56);
  gtk_widget_set_size_request (labelnom_produit, 73, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelnom_produit), TRUE);

  labeldate_produit = gtk_label_new (_("<span foreground=\"black\"><b>date d'ajout</b></span>"));
  gtk_widget_show (labeldate_produit);
  gtk_fixed_put (GTK_FIXED (fixed1), labeldate_produit, 80, 192);
  gtk_widget_set_size_request (labeldate_produit, 96, 16);
  gtk_label_set_use_markup (GTK_LABEL (labeldate_produit), TRUE);

  labeltype_produit = gtk_label_new (_("<span foreground=\"black\"><b>Type</b></span>"));
  gtk_widget_show (labeltype_produit);
  gtk_fixed_put (GTK_FIXED (fixed1), labeltype_produit, 112, 112);
  gtk_widget_set_size_request (labeltype_produit, 41, 17);
  gtk_label_set_use_markup (GTK_LABEL (labeltype_produit), TRUE);

  labelquantit___produit = gtk_label_new (_("<span foreground=\"black\"><b>Quantit\303\251 </b></span>"));
  gtk_widget_show (labelquantit___produit);
  gtk_fixed_put (GTK_FIXED (fixed1), labelquantit___produit, 96, 280);
  gtk_widget_set_size_request (labelquantit___produit, 64, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelquantit___produit), TRUE);

  labelprix_produit = gtk_label_new (_("<span foreground=\"black\"><b>Prix unitaire </b></span>"));
  gtk_widget_show (labelprix_produit);
  gtk_fixed_put (GTK_FIXED (fixed1), labelprix_produit, 72, 344);
  gtk_widget_set_size_request (labelprix_produit, 104, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelprix_produit), TRUE);

  Ajouter_Produit = gtk_button_new ();
  gtk_widget_show (Ajouter_Produit);
  gtk_fixed_put (GTK_FIXED (fixed1), Ajouter_Produit, 488, 392);
  gtk_widget_set_size_request (Ajouter_Produit, 104, 45);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (Ajouter_Produit), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox1), label7, FALSE, FALSE, 0);

  comboboxtypep = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxtypep);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxtypep, 215, 103);
  gtk_widget_set_size_request (comboboxtypep, 211, 30);

  labelerreurnom = gtk_label_new (_("<span foreground=\"red\"><b>champ obligatoire *</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed1), labelerreurnom, 456, 56);
  gtk_widget_set_size_request (labelerreurnom, 144, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelerreurnom), TRUE);

  labelerreurquantite = gtk_label_new (_("<span foreground=\"red\"><b>champ obligatoire *</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed1), labelerreurquantite, 456, 272);
  gtk_widget_set_size_request (labelerreurquantite, 152, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelerreurquantite), TRUE);

  labelerreurprixunitaire = gtk_label_new (_("<span foreground=\"red\"><b>champ obligatoire *</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed1), labelerreurprixunitaire, 456, 344);
  gtk_widget_set_size_request (labelerreurprixunitaire, 152, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelerreurprixunitaire), TRUE);

  g_signal_connect ((gpointer) Pr__c__dent_ajouter_afficher_produit, "clicked",
                    G_CALLBACK (on_Pr__c__dent_ajouter_afficher_produit_clicked),
                    NULL);
  g_signal_connect ((gpointer) ok, "clicked",
                    G_CALLBACK (on_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) Ajouter_Produit, "clicked",
                    G_CALLBACK (on_Ajouter_Produit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_produit, ajout_produit, "ajout_produit");
  GLADE_HOOKUP_OBJECT (ajout_produit, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (ajout_produit, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajout_produit, entryQuantite_Produit, "entryQuantite_Produit");
  GLADE_HOOKUP_OBJECT (ajout_produit, entryNom_Produit, "entryNom_Produit");
  GLADE_HOOKUP_OBJECT (ajout_produit, entryPrixunitaire_Produit, "entryPrixunitaire_Produit");
  GLADE_HOOKUP_OBJECT (ajout_produit, spinbutton_jourajoutproduit, "spinbutton_jourajoutproduit");
  GLADE_HOOKUP_OBJECT (ajout_produit, spinbutton_moisajoutproduit, "spinbutton_moisajoutproduit");
  GLADE_HOOKUP_OBJECT (ajout_produit, spinbutton_anneeajoutproduit, "spinbutton_anneeajoutproduit");
  GLADE_HOOKUP_OBJECT (ajout_produit, image16, "image16");
  GLADE_HOOKUP_OBJECT (ajout_produit, Pr__c__dent_ajouter_afficher_produit, "Pr__c__dent_ajouter_afficher_produit");
  GLADE_HOOKUP_OBJECT (ajout_produit, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (ajout_produit, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (ajout_produit, image7, "image7");
  GLADE_HOOKUP_OBJECT (ajout_produit, label21, "label21");
  GLADE_HOOKUP_OBJECT (ajout_produit, ok, "ok");
  GLADE_HOOKUP_OBJECT (ajout_produit, image14, "image14");
  GLADE_HOOKUP_OBJECT (ajout_produit, label13, "label13");
  GLADE_HOOKUP_OBJECT (ajout_produit, labelannee, "labelannee");
  GLADE_HOOKUP_OBJECT (ajout_produit, labeljour, "labeljour");
  GLADE_HOOKUP_OBJECT (ajout_produit, labelmois, "labelmois");
  GLADE_HOOKUP_OBJECT (ajout_produit, labelnom_produit, "labelnom_produit");
  GLADE_HOOKUP_OBJECT (ajout_produit, labeldate_produit, "labeldate_produit");
  GLADE_HOOKUP_OBJECT (ajout_produit, labeltype_produit, "labeltype_produit");
  GLADE_HOOKUP_OBJECT (ajout_produit, labelquantit___produit, "labelquantit___produit");
  GLADE_HOOKUP_OBJECT (ajout_produit, labelprix_produit, "labelprix_produit");
  GLADE_HOOKUP_OBJECT (ajout_produit, Ajouter_Produit, "Ajouter_Produit");
  GLADE_HOOKUP_OBJECT (ajout_produit, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (ajout_produit, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ajout_produit, image1, "image1");
  GLADE_HOOKUP_OBJECT (ajout_produit, label7, "label7");
  GLADE_HOOKUP_OBJECT (ajout_produit, comboboxtypep, "comboboxtypep");
  GLADE_HOOKUP_OBJECT (ajout_produit, labelerreurnom, "labelerreurnom");
  GLADE_HOOKUP_OBJECT (ajout_produit, labelerreurquantite, "labelerreurquantite");
  GLADE_HOOKUP_OBJECT (ajout_produit, labelerreurprixunitaire, "labelerreurprixunitaire");

  return ajout_produit;
}

GtkWidget*
create_Afficher_produit (void)
{
  GtkWidget *Afficher_produit;
  GtkWidget *fixed2;
  GtkWidget *entry_nomp;
  GtkWidget *entry_idp;
  GtkWidget *button_recherche_produit;
  GtkWidget *image12;
  GtkWidget *button1;
  GtkWidget *image13;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *Liste_des_produit;
  GtkWidget *label29;
  GtkWidget *label28;
  GtkWidget *button_afficher_supprimer_produit;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label12;
  GtkWidget *button_afficher_modifier_produit;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label11;
  GtkWidget *button_afficher_ajouter_produit;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label9;
  GtkWidget *buttonafficher_acceuil;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label10;

  Afficher_produit = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Afficher_produit, 650, 464);
  gtk_window_set_title (GTK_WINDOW (Afficher_produit), _("Afficher_produit"));
  gtk_window_set_position (GTK_WINDOW (Afficher_produit), GTK_WIN_POS_CENTER);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Afficher_produit), fixed2);
  gtk_widget_set_size_request (fixed2, 650, 464);

  entry_nomp = gtk_entry_new ();
  gtk_widget_show (entry_nomp);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_nomp, 344, 40);
  gtk_widget_set_size_request (entry_nomp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nomp), 8226);

  entry_idp = gtk_entry_new ();
  gtk_widget_show (entry_idp);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_idp, 104, 40);
  gtk_widget_set_size_request (entry_idp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idp), 8226);

  button_recherche_produit = gtk_button_new ();
  gtk_widget_show (button_recherche_produit);
  gtk_fixed_put (GTK_FIXED (fixed2), button_recherche_produit, 512, 40);
  gtk_widget_set_size_request (button_recherche_produit, 66, 29);

  image12 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_container_add (GTK_CONTAINER (button_recherche_produit), image12);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed2), button1, 600, 8);
  gtk_widget_set_size_request (button1, 24, 24);

  image13 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_container_add (GTK_CONTAINER (button1), image13);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed2), scrolledwindow1, 16, 80);
  gtk_widget_set_size_request (scrolledwindow1, 608, 304);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_widget_set_size_request (treeview1, 608, 304);

  Liste_des_produit = gtk_label_new (_("<span foreground=\"blue\"><b>liste des produits</b> </span>"));
  gtk_widget_show (Liste_des_produit);
  gtk_fixed_put (GTK_FIXED (fixed2), Liste_des_produit, 200, 0);
  gtk_widget_set_size_request (Liste_des_produit, 248, 40);
  gtk_label_set_use_markup (GTK_LABEL (Liste_des_produit), TRUE);

  label29 = gtk_label_new (_("<span foreground=\"bLACK\"><b>ID : </b> </span>"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed2), label29, 64, 40);
  gtk_widget_set_size_request (label29, 40, 32);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  label28 = gtk_label_new (_("<span foreground=\"bLACK\"><b> NOM : </b> </span>"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed2), label28, 280, 48);
  gtk_widget_set_size_request (label28, 56, 17);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  button_afficher_supprimer_produit = gtk_button_new ();
  gtk_widget_show (button_afficher_supprimer_produit);
  gtk_fixed_put (GTK_FIXED (fixed2), button_afficher_supprimer_produit, 480, 416);
  gtk_widget_set_size_request (button_afficher_supprimer_produit, 120, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_afficher_supprimer_produit), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Supprimer "));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox5), label12, FALSE, FALSE, 0);

  button_afficher_modifier_produit = gtk_button_new ();
  gtk_widget_show (button_afficher_modifier_produit);
  gtk_fixed_put (GTK_FIXED (fixed2), button_afficher_modifier_produit, 336, 416);
  gtk_widget_set_size_request (button_afficher_modifier_produit, 120, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_afficher_modifier_produit), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox4), label11, FALSE, FALSE, 0);

  button_afficher_ajouter_produit = gtk_button_new ();
  gtk_widget_show (button_afficher_ajouter_produit);
  gtk_fixed_put (GTK_FIXED (fixed2), button_afficher_ajouter_produit, 184, 416);
  gtk_widget_set_size_request (button_afficher_ajouter_produit, 120, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_afficher_ajouter_produit), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox2), label9, FALSE, FALSE, 0);

  buttonafficher_acceuil = gtk_button_new ();
  gtk_widget_show (buttonafficher_acceuil);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonafficher_acceuil, 32, 416);
  gtk_widget_set_size_request (buttonafficher_acceuil, 120, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonafficher_acceuil), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("pr\303\251c\303\251dent"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox3), label10, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_recherche_produit, "clicked",
                    G_CALLBACK (on_button_recherche_produit_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button_afficher_supprimer_produit, "clicked",
                    G_CALLBACK (on_button_afficher_supprimer_produit_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_afficher_modifier_produit, "clicked",
                    G_CALLBACK (on_button_afficher_modifier_produit_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_afficher_ajouter_produit, "clicked",
                    G_CALLBACK (on_button_afficher_ajouter_produit_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonafficher_acceuil, "clicked",
                    G_CALLBACK (on_buttonafficher_acceuil_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Afficher_produit, Afficher_produit, "Afficher_produit");
  GLADE_HOOKUP_OBJECT (Afficher_produit, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Afficher_produit, entry_nomp, "entry_nomp");
  GLADE_HOOKUP_OBJECT (Afficher_produit, entry_idp, "entry_idp");
  GLADE_HOOKUP_OBJECT (Afficher_produit, button_recherche_produit, "button_recherche_produit");
  GLADE_HOOKUP_OBJECT (Afficher_produit, image12, "image12");
  GLADE_HOOKUP_OBJECT (Afficher_produit, button1, "button1");
  GLADE_HOOKUP_OBJECT (Afficher_produit, image13, "image13");
  GLADE_HOOKUP_OBJECT (Afficher_produit, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (Afficher_produit, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Afficher_produit, Liste_des_produit, "Liste_des_produit");
  GLADE_HOOKUP_OBJECT (Afficher_produit, label29, "label29");
  GLADE_HOOKUP_OBJECT (Afficher_produit, label28, "label28");
  GLADE_HOOKUP_OBJECT (Afficher_produit, button_afficher_supprimer_produit, "button_afficher_supprimer_produit");
  GLADE_HOOKUP_OBJECT (Afficher_produit, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Afficher_produit, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Afficher_produit, image5, "image5");
  GLADE_HOOKUP_OBJECT (Afficher_produit, label12, "label12");
  GLADE_HOOKUP_OBJECT (Afficher_produit, button_afficher_modifier_produit, "button_afficher_modifier_produit");
  GLADE_HOOKUP_OBJECT (Afficher_produit, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Afficher_produit, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Afficher_produit, image4, "image4");
  GLADE_HOOKUP_OBJECT (Afficher_produit, label11, "label11");
  GLADE_HOOKUP_OBJECT (Afficher_produit, button_afficher_ajouter_produit, "button_afficher_ajouter_produit");
  GLADE_HOOKUP_OBJECT (Afficher_produit, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Afficher_produit, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Afficher_produit, image2, "image2");
  GLADE_HOOKUP_OBJECT (Afficher_produit, label9, "label9");
  GLADE_HOOKUP_OBJECT (Afficher_produit, buttonafficher_acceuil, "buttonafficher_acceuil");
  GLADE_HOOKUP_OBJECT (Afficher_produit, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Afficher_produit, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Afficher_produit, image3, "image3");
  GLADE_HOOKUP_OBJECT (Afficher_produit, label10, "label10");

  return Afficher_produit;
}

GtkWidget*
create_modifie_produit (void)
{
  GtkWidget *modifie_produit;
  GtkWidget *fixed3;
  GtkWidget *entrynom_produit;
  GtkWidget *entryquantite_produit;
  GtkWidget *entryprixunitaire_produit;
  GtkWidget *labelid_produit;
  GtkWidget *labelnom_produit;
  GtkWidget *labeltype_produit;
  GtkWidget *labelquantite_produit;
  GtkWidget *labelprix_produit;
  GtkWidget *labeldate_produit;
  GtkWidget *labelid;
  GtkWidget *labeldatedajout;
  GtkWidget *button_modifier_afficher_produit;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label22;
  GtkWidget *modifier_produit;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label20;
  GtkWidget *button3;
  GtkWidget *image36;
  GtkWidget *comboboxmodifiertypep;

  modifie_produit = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modifie_produit, 650, 464);
  gtk_window_set_title (GTK_WINDOW (modifie_produit), _("modifie_produit"));
  gtk_window_set_position (GTK_WINDOW (modifie_produit), GTK_WIN_POS_CENTER);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (modifie_produit), fixed3);
  gtk_widget_set_size_request (fixed3, 650, 464);

  entrynom_produit = gtk_entry_new ();
  gtk_widget_show (entrynom_produit);
  gtk_fixed_put (GTK_FIXED (fixed3), entrynom_produit, 272, 56);
  gtk_widget_set_size_request (entrynom_produit, 240, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom_produit), 8226);

  entryquantite_produit = gtk_entry_new ();
  gtk_widget_show (entryquantite_produit);
  gtk_fixed_put (GTK_FIXED (fixed3), entryquantite_produit, 272, 176);
  gtk_widget_set_size_request (entryquantite_produit, 240, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryquantite_produit), 8226);

  entryprixunitaire_produit = gtk_entry_new ();
  gtk_widget_show (entryprixunitaire_produit);
  gtk_fixed_put (GTK_FIXED (fixed3), entryprixunitaire_produit, 272, 240);
  gtk_widget_set_size_request (entryprixunitaire_produit, 240, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprixunitaire_produit), 8226);

  labelid_produit = gtk_label_new (_("<span foreground=\"BLACK\"><b>ID : </b> </span>"));
  gtk_widget_show (labelid_produit);
  gtk_fixed_put (GTK_FIXED (fixed3), labelid_produit, 144, 16);
  gtk_widget_set_size_request (labelid_produit, 72, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelid_produit), TRUE);

  labelnom_produit = gtk_label_new (_("<span foreground=\"BLACK\"><b>NOM : </b> </span>"));
  gtk_widget_show (labelnom_produit);
  gtk_fixed_put (GTK_FIXED (fixed3), labelnom_produit, 136, 64);
  gtk_widget_set_size_request (labelnom_produit, 88, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelnom_produit), TRUE);

  labeltype_produit = gtk_label_new (_("<span foreground=\"bLACK\"><b> TYPE :</b> </span>"));
  gtk_widget_show (labeltype_produit);
  gtk_fixed_put (GTK_FIXED (fixed3), labeltype_produit, 144, 128);
  gtk_widget_set_size_request (labeltype_produit, 64, 17);
  gtk_label_set_use_markup (GTK_LABEL (labeltype_produit), TRUE);

  labelquantite_produit = gtk_label_new (_("<span foreground=\"BLACK\"><b> QUANTIT\303\211 :</b> </span>"));
  gtk_widget_show (labelquantite_produit);
  gtk_fixed_put (GTK_FIXED (fixed3), labelquantite_produit, 128, 184);
  gtk_widget_set_size_request (labelquantite_produit, 104, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelquantite_produit), TRUE);

  labelprix_produit = gtk_label_new (_("<span foreground=\"bLACK\"><b> PRIX UNITAIRE :</b> </span>"));
  gtk_widget_show (labelprix_produit);
  gtk_fixed_put (GTK_FIXED (fixed3), labelprix_produit, 112, 248);
  gtk_widget_set_size_request (labelprix_produit, 128, 33);
  gtk_label_set_use_markup (GTK_LABEL (labelprix_produit), TRUE);

  labeldate_produit = gtk_label_new (_("<span foreground=\"BLACK\"><b> DATE D'AJOUT : </b> </span>"));
  gtk_widget_show (labeldate_produit);
  gtk_fixed_put (GTK_FIXED (fixed3), labeldate_produit, 112, 312);
  gtk_widget_set_size_request (labeldate_produit, 128, 25);
  gtk_label_set_use_markup (GTK_LABEL (labeldate_produit), TRUE);

  labelid = gtk_label_new (_("<span foreground=\"BLACK\"><b>labelid </b> </span>"));
  gtk_widget_show (labelid);
  gtk_fixed_put (GTK_FIXED (fixed3), labelid, 336, 16);
  gtk_widget_set_size_request (labelid, 104, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelid), TRUE);

  labeldatedajout = gtk_label_new (_("<span foreground=\"black\"><b>labeldatedajout</b> </span> "));
  gtk_widget_show (labeldatedajout);
  gtk_fixed_put (GTK_FIXED (fixed3), labeldatedajout, 320, 312);
  gtk_widget_set_size_request (labeldatedajout, 168, 17);
  gtk_label_set_use_markup (GTK_LABEL (labeldatedajout), TRUE);

  button_modifier_afficher_produit = gtk_button_new ();
  gtk_widget_show (button_modifier_afficher_produit);
  gtk_fixed_put (GTK_FIXED (fixed3), button_modifier_afficher_produit, 88, 392);
  gtk_widget_set_size_request (button_modifier_afficher_produit, 106, 53);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_modifier_afficher_produit), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("pr\303\251c\303\251dent"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox8), label22, FALSE, FALSE, 0);

  modifier_produit = gtk_button_new ();
  gtk_widget_show (modifier_produit);
  gtk_fixed_put (GTK_FIXED (fixed3), modifier_produit, 464, 392);
  gtk_widget_set_size_request (modifier_produit, 120, 53);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (modifier_produit), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("modifier "));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox6), label20, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed3), button3, 544, 112);
  gtk_widget_set_size_request (button3, 42, 29);

  image36 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_container_add (GTK_CONTAINER (button3), image36);

  comboboxmodifiertypep = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxmodifiertypep);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxmodifiertypep, 281, 116);
  gtk_widget_set_size_request (comboboxmodifiertypep, 228, 33);

  g_signal_connect ((gpointer) button_modifier_afficher_produit, "clicked",
                    G_CALLBACK (on_button_modifier_afficher_produit_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_produit, "clicked",
                    G_CALLBACK (on_modifier_produit_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifie_produit, modifie_produit, "modifie_produit");
  GLADE_HOOKUP_OBJECT (modifie_produit, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (modifie_produit, entrynom_produit, "entrynom_produit");
  GLADE_HOOKUP_OBJECT (modifie_produit, entryquantite_produit, "entryquantite_produit");
  GLADE_HOOKUP_OBJECT (modifie_produit, entryprixunitaire_produit, "entryprixunitaire_produit");
  GLADE_HOOKUP_OBJECT (modifie_produit, labelid_produit, "labelid_produit");
  GLADE_HOOKUP_OBJECT (modifie_produit, labelnom_produit, "labelnom_produit");
  GLADE_HOOKUP_OBJECT (modifie_produit, labeltype_produit, "labeltype_produit");
  GLADE_HOOKUP_OBJECT (modifie_produit, labelquantite_produit, "labelquantite_produit");
  GLADE_HOOKUP_OBJECT (modifie_produit, labelprix_produit, "labelprix_produit");
  GLADE_HOOKUP_OBJECT (modifie_produit, labeldate_produit, "labeldate_produit");
  GLADE_HOOKUP_OBJECT (modifie_produit, labelid, "labelid");
  GLADE_HOOKUP_OBJECT (modifie_produit, labeldatedajout, "labeldatedajout");
  GLADE_HOOKUP_OBJECT (modifie_produit, button_modifier_afficher_produit, "button_modifier_afficher_produit");
  GLADE_HOOKUP_OBJECT (modifie_produit, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (modifie_produit, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (modifie_produit, image8, "image8");
  GLADE_HOOKUP_OBJECT (modifie_produit, label22, "label22");
  GLADE_HOOKUP_OBJECT (modifie_produit, modifier_produit, "modifier_produit");
  GLADE_HOOKUP_OBJECT (modifie_produit, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (modifie_produit, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (modifie_produit, image6, "image6");
  GLADE_HOOKUP_OBJECT (modifie_produit, label20, "label20");
  GLADE_HOOKUP_OBJECT (modifie_produit, button3, "button3");
  GLADE_HOOKUP_OBJECT (modifie_produit, image36, "image36");
  GLADE_HOOKUP_OBJECT (modifie_produit, comboboxmodifiertypep, "comboboxmodifiertypep");

  return modifie_produit;
}

GtkWidget*
create_supprimer_produit (void)
{
  GtkWidget *supprimer_produit;
  GtkWidget *fixed4;
  GtkWidget *labelsupprimer_produit;
  GtkWidget *button_supprimer_afficher_produit;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label25;
  GtkWidget *supprimer_produit_;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label26;

  supprimer_produit = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (supprimer_produit, 800, 500);
  gtk_window_set_title (GTK_WINDOW (supprimer_produit), _("supprimer_produit"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (supprimer_produit), fixed4);
  gtk_widget_set_size_request (fixed4, 800, 500);

  labelsupprimer_produit = gtk_label_new (_("voulez vous supprimer le produit "));
  gtk_widget_show (labelsupprimer_produit);
  gtk_fixed_put (GTK_FIXED (fixed4), labelsupprimer_produit, 160, 80);
  gtk_widget_set_size_request (labelsupprimer_produit, 400, 112);

  button_supprimer_afficher_produit = gtk_button_new ();
  gtk_widget_show (button_supprimer_afficher_produit);
  gtk_fixed_put (GTK_FIXED (fixed4), button_supprimer_afficher_produit, 120, 248);
  gtk_widget_set_size_request (button_supprimer_afficher_produit, 120, 45);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_supprimer_afficher_produit), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Non"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox10), label25, FALSE, FALSE, 0);

  supprimer_produit_ = gtk_button_new ();
  gtk_widget_show (supprimer_produit_);
  gtk_fixed_put (GTK_FIXED (fixed4), supprimer_produit_, 464, 240);
  gtk_widget_set_size_request (supprimer_produit_, 114, 45);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (supprimer_produit_), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Oui"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox11), label26, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer_produit, supprimer_produit, "supprimer_produit");
  GLADE_HOOKUP_OBJECT (supprimer_produit, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (supprimer_produit, labelsupprimer_produit, "labelsupprimer_produit");
  GLADE_HOOKUP_OBJECT (supprimer_produit, button_supprimer_afficher_produit, "button_supprimer_afficher_produit");
  GLADE_HOOKUP_OBJECT (supprimer_produit, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (supprimer_produit, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (supprimer_produit, image10, "image10");
  GLADE_HOOKUP_OBJECT (supprimer_produit, label25, "label25");
  GLADE_HOOKUP_OBJECT (supprimer_produit, supprimer_produit_, "supprimer_produit_");
  GLADE_HOOKUP_OBJECT (supprimer_produit, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (supprimer_produit, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (supprimer_produit, image11, "image11");
  GLADE_HOOKUP_OBJECT (supprimer_produit, label26, "label26");

  return supprimer_produit;
}

GtkWidget*
create_employe (void)
{
  GtkWidget *employe;
  GtkWidget *fixed5;
  GtkWidget *image34;
  GtkWidget *buttongestionproduits;
  GtkWidget *button_precedent_employe_accueil;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image29;
  GtkWidget *label51;
  GtkWidget *button2;
  GtkWidget *image27;
  GtkWidget *labelemploye;

  employe = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (employe, 624, 472);
  gtk_window_set_title (GTK_WINDOW (employe), _("employ\303\251"));
  gtk_window_set_position (GTK_WINDOW (employe), GTK_WIN_POS_CENTER);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (employe), fixed5);
  gtk_widget_set_size_request (fixed5, 624, 472);

  image34 = create_pixmap (employe, "agricultrice-travaillant-tablette_202279-134.jpeg");
  gtk_widget_show (image34);
  gtk_fixed_put (GTK_FIXED (fixed5), image34, 0, 0);
  gtk_widget_set_size_request (image34, 624, 472);

  buttongestionproduits = gtk_button_new_with_mnemonic (_("Gestion des produits"));
  gtk_widget_show (buttongestionproduits);
  gtk_fixed_put (GTK_FIXED (fixed5), buttongestionproduits, 248, 200);
  gtk_widget_set_size_request (buttongestionproduits, 280, 72);

  button_precedent_employe_accueil = gtk_button_new ();
  gtk_widget_show (button_precedent_employe_accueil);
  gtk_fixed_put (GTK_FIXED (fixed5), button_precedent_employe_accueil, 72, 424);
  gtk_widget_set_size_request (button_precedent_employe_accueil, 128, 37);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button_precedent_employe_accueil), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image29 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox19), image29, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("Pr\303\251c\303\251dent"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox19), label51, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed5), button2, 568, 432);
  gtk_widget_set_size_request (button2, 40, 24);

  image27 = create_pixmap (employe, "mail.png");
  gtk_widget_show (image27);
  gtk_container_add (GTK_CONTAINER (button2), image27);

  labelemploye = gtk_label_new (_("<span foreground=\"blue\"><b> BIENVENUE MONSIEUR  L'EMPLOY\303\211 !  </b> </span>"));
  gtk_widget_show (labelemploye);
  gtk_fixed_put (GTK_FIXED (fixed5), labelemploye, 144, 8);
  gtk_widget_set_size_request (labelemploye, 352, 112);
  gtk_label_set_use_markup (GTK_LABEL (labelemploye), TRUE);

  g_signal_connect ((gpointer) buttongestionproduits, "clicked",
                    G_CALLBACK (on_buttongestionproduits_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_precedent_employe_accueil, "clicked",
                    G_CALLBACK (on_buttonprecedentemployeaccueil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (employe, employe, "employe");
  GLADE_HOOKUP_OBJECT (employe, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (employe, image34, "image34");
  GLADE_HOOKUP_OBJECT (employe, buttongestionproduits, "buttongestionproduits");
  GLADE_HOOKUP_OBJECT (employe, button_precedent_employe_accueil, "button_precedent_employe_accueil");
  GLADE_HOOKUP_OBJECT (employe, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (employe, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (employe, image29, "image29");
  GLADE_HOOKUP_OBJECT (employe, label51, "label51");
  GLADE_HOOKUP_OBJECT (employe, button2, "button2");
  GLADE_HOOKUP_OBJECT (employe, image27, "image27");
  GLADE_HOOKUP_OBJECT (employe, labelemploye, "labelemploye");

  return employe;
}

GtkWidget*
create_ajout_employe (void)
{
  GtkWidget *ajout_employe;
  GtkWidget *fixed6;
  GtkWidget *entrynomemploye;
  GtkWidget *entryprenomemploye;
  GtkWidget *entrycinemploye;
  GtkObject *spinbutton_jouremploye_adj;
  GtkWidget *spinbutton_jouremploye;
  GtkObject *spinbutton_moisemploye_adj;
  GtkWidget *spinbutton_moisemploye;
  GtkObject *spinbutton_anneeemploye_adj;
  GtkWidget *spinbutton_anneeemploye;
  GtkWidget *entryadresseemploye;
  GtkObject *spinbutton_jourajoutemploye_adj;
  GtkWidget *spinbutton_jourajoutemploye;
  GtkObject *spinbutton_moisajoutemploye_adj;
  GtkWidget *spinbutton_moisajoutemploye;
  GtkObject *spinbutton_anneeajoutemploye_adj;
  GtkWidget *spinbutton_anneeajoutemploye;
  GtkWidget *entrysalaireactuelemploye;
  GtkWidget *buttonajouteremploye;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image17;
  GtkWidget *label41;
  GtkWidget *buttonprecedentajouterafficheremploye;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image18;
  GtkWidget *label42;
  GtkWidget *comboboxspecialite;
  GtkWidget *comboboxsituation;
  GtkWidget *comboboxsexe;
  GtkWidget *labelnom;
  GtkWidget *labelprenom;
  GtkWidget *labeldatenaissance;
  GtkWidget *labelsexe;
  GtkWidget *labelciN;
  GtkWidget *labeladresse;
  GtkWidget *labelsituationfamiliale;
  GtkWidget *labeldateembauche;
  GtkWidget *labelsalaireactuel;
  GtkWidget *labelspecialite;

  ajout_employe = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajout_employe, 750, 520);
  gtk_window_set_title (GTK_WINDOW (ajout_employe), _("ajouter employ\303\251"));
  gtk_window_set_position (GTK_WINDOW (ajout_employe), GTK_WIN_POS_CENTER);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (ajout_employe), fixed6);
  gtk_widget_set_size_request (fixed6, 750, 520);

  entrynomemploye = gtk_entry_new ();
  gtk_widget_show (entrynomemploye);
  gtk_fixed_put (GTK_FIXED (fixed6), entrynomemploye, 256, 32);
  gtk_widget_set_size_request (entrynomemploye, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynomemploye), 8226);

  entryprenomemploye = gtk_entry_new ();
  gtk_widget_show (entryprenomemploye);
  gtk_fixed_put (GTK_FIXED (fixed6), entryprenomemploye, 256, 72);
  gtk_widget_set_size_request (entryprenomemploye, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenomemploye), 8226);

  entrycinemploye = gtk_entry_new ();
  gtk_widget_show (entrycinemploye);
  gtk_fixed_put (GTK_FIXED (fixed6), entrycinemploye, 264, 192);
  gtk_widget_set_size_request (entrycinemploye, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycinemploye), 8226);

  spinbutton_jouremploye_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_jouremploye = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_jouremploye_adj), 1, 0);
  gtk_widget_show (spinbutton_jouremploye);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton_jouremploye, 264, 112);
  gtk_widget_set_size_request (spinbutton_jouremploye, 60, 27);

  spinbutton_moisemploye_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_moisemploye = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_moisemploye_adj), 1, 0);
  gtk_widget_show (spinbutton_moisemploye);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton_moisemploye, 344, 112);
  gtk_widget_set_size_request (spinbutton_moisemploye, 60, 27);

  spinbutton_anneeemploye_adj = gtk_adjustment_new (1, 2020, 2050, 1, 10, 10);
  spinbutton_anneeemploye = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_anneeemploye_adj), 1, 0);
  gtk_widget_show (spinbutton_anneeemploye);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton_anneeemploye, 424, 112);
  gtk_widget_set_size_request (spinbutton_anneeemploye, 60, 27);

  entryadresseemploye = gtk_entry_new ();
  gtk_widget_show (entryadresseemploye);
  gtk_fixed_put (GTK_FIXED (fixed6), entryadresseemploye, 264, 232);
  gtk_widget_set_size_request (entryadresseemploye, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryadresseemploye), 8226);

  spinbutton_jourajoutemploye_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_jourajoutemploye = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_jourajoutemploye_adj), 1, 0);
  gtk_widget_show (spinbutton_jourajoutemploye);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton_jourajoutemploye, 264, 320);
  gtk_widget_set_size_request (spinbutton_jourajoutemploye, 60, 27);

  spinbutton_moisajoutemploye_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_moisajoutemploye = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_moisajoutemploye_adj), 1, 0);
  gtk_widget_show (spinbutton_moisajoutemploye);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton_moisajoutemploye, 336, 320);
  gtk_widget_set_size_request (spinbutton_moisajoutemploye, 60, 27);

  spinbutton_anneeajoutemploye_adj = gtk_adjustment_new (1, 2020, 2050, 1, 10, 10);
  spinbutton_anneeajoutemploye = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_anneeajoutemploye_adj), 1, 0);
  gtk_widget_show (spinbutton_anneeajoutemploye);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton_anneeajoutemploye, 416, 320);
  gtk_widget_set_size_request (spinbutton_anneeajoutemploye, 60, 27);

  entrysalaireactuelemploye = gtk_entry_new ();
  gtk_widget_show (entrysalaireactuelemploye);
  gtk_fixed_put (GTK_FIXED (fixed6), entrysalaireactuelemploye, 264, 376);
  gtk_widget_set_size_request (entrysalaireactuelemploye, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrysalaireactuelemploye), 8226);

  buttonajouteremploye = gtk_button_new ();
  gtk_widget_show (buttonajouteremploye);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonajouteremploye, 496, 472);
  gtk_widget_set_size_request (buttonajouteremploye, 128, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonajouteremploye), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image17 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox12), image17, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Ajouter "));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox12), label41, FALSE, FALSE, 0);

  buttonprecedentajouterafficheremploye = gtk_button_new ();
  gtk_widget_show (buttonprecedentajouterafficheremploye);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonprecedentajouterafficheremploye, 24, 472);
  gtk_widget_set_size_request (buttonprecedentajouterafficheremploye, 106, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (buttonprecedentajouterafficheremploye), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox13), image18, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Pr\303\251c\303\251dent "));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox13), label42, FALSE, FALSE, 0);

  comboboxspecialite = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxspecialite);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxspecialite, 269, 423);
  gtk_widget_set_size_request (comboboxspecialite, 132, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxspecialite), _("ingenieur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxspecialite), _("veterinaire"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxspecialite), _("electricien "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxspecialite), _("agriculteur "));

  comboboxsituation = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxsituation);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxsituation, 272, 274);
  gtk_widget_set_size_request (comboboxsituation, 125, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxsituation), _("celibataire"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxsituation), _("mari\303\251"));

  comboboxsexe = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxsexe);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxsexe, 270, 150);
  gtk_widget_set_size_request (comboboxsexe, 124, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxsexe), _("male"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxsexe), _("female"));

  labelnom = gtk_label_new (_("<span foreground=\"BLACK\"><b> NOM : </b> </span>"));
  gtk_widget_show (labelnom);
  gtk_fixed_put (GTK_FIXED (fixed6), labelnom, 168, 40);
  gtk_widget_set_size_request (labelnom, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelnom), TRUE);

  labelprenom = gtk_label_new (_("<span foreground=\"BLACK\"><b> PR\303\211NOM :</b> </span>"));
  gtk_widget_show (labelprenom);
  gtk_fixed_put (GTK_FIXED (fixed6), labelprenom, 136, 80);
  gtk_widget_set_size_request (labelprenom, 89, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelprenom), TRUE);

  labeldatenaissance = gtk_label_new (_("<span foreground=\"BLACK\"><b> DATE DE NAISSANCE :</b> </span>"));
  gtk_widget_show (labeldatenaissance);
  gtk_fixed_put (GTK_FIXED (fixed6), labeldatenaissance, 64, 112);
  gtk_widget_set_size_request (labeldatenaissance, 184, 25);
  gtk_label_set_use_markup (GTK_LABEL (labeldatenaissance), TRUE);

  labelsexe = gtk_label_new (_("<span foreground=\"BLACK\"><b> SEXE :</b> </span>"));
  gtk_widget_show (labelsexe);
  gtk_fixed_put (GTK_FIXED (fixed6), labelsexe, 144, 160);
  gtk_widget_set_size_request (labelsexe, 80, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelsexe), TRUE);

  labelciN = gtk_label_new (_("<span foreground=\"BLACK\"><b> C.I.N :</b> </span>"));
  gtk_widget_show (labelciN);
  gtk_fixed_put (GTK_FIXED (fixed6), labelciN, 144, 192);
  gtk_widget_set_size_request (labelciN, 72, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelciN), TRUE);

  labeladresse = gtk_label_new (_("<span foreground=\"BLACK\"><b>ADRESSE : </b> </span>"));
  gtk_widget_show (labeladresse);
  gtk_fixed_put (GTK_FIXED (fixed6), labeladresse, 128, 232);
  gtk_widget_set_size_request (labeladresse, 88, 25);
  gtk_label_set_use_markup (GTK_LABEL (labeladresse), TRUE);

  labelsituationfamiliale = gtk_label_new (_("<span foreground=\"BLACK\"><b> SITUATION FAMILIALE :</b> </span>"));
  gtk_widget_show (labelsituationfamiliale);
  gtk_fixed_put (GTK_FIXED (fixed6), labelsituationfamiliale, 56, 280);
  gtk_widget_set_size_request (labelsituationfamiliale, 200, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelsituationfamiliale), TRUE);

  labeldateembauche = gtk_label_new (_("<span foreground=\"BLACK\"><b> DATE D'EMBAUCHE :</b> </span>"));
  gtk_widget_show (labeldateembauche);
  gtk_fixed_put (GTK_FIXED (fixed6), labeldateembauche, 64, 320);
  gtk_widget_set_size_request (labeldateembauche, 177, 25);
  gtk_label_set_use_markup (GTK_LABEL (labeldateembauche), TRUE);

  labelsalaireactuel = gtk_label_new (_("<span foreground=\"BLACK\"><b> SALAIRE ACTUEL : </b> </span>"));
  gtk_widget_show (labelsalaireactuel);
  gtk_fixed_put (GTK_FIXED (fixed6), labelsalaireactuel, 56, 384);
  gtk_widget_set_size_request (labelsalaireactuel, 192, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelsalaireactuel), TRUE);

  labelspecialite = gtk_label_new (_("<span foreground=\"BLACK\"><b> SPECIALIT\303\211 :</b> </span>"));
  gtk_widget_show (labelspecialite);
  gtk_fixed_put (GTK_FIXED (fixed6), labelspecialite, 72, 432);
  gtk_widget_set_size_request (labelspecialite, 153, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelspecialite), TRUE);

  g_signal_connect ((gpointer) buttonajouteremploye, "clicked",
                    G_CALLBACK (on_buttonajouteremploye_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonprecedentajouterafficheremploye, "clicked",
                    G_CALLBACK (on_buttonprecedentajouterafficheremploye_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_employe, ajout_employe, "ajout_employe");
  GLADE_HOOKUP_OBJECT (ajout_employe, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (ajout_employe, entrynomemploye, "entrynomemploye");
  GLADE_HOOKUP_OBJECT (ajout_employe, entryprenomemploye, "entryprenomemploye");
  GLADE_HOOKUP_OBJECT (ajout_employe, entrycinemploye, "entrycinemploye");
  GLADE_HOOKUP_OBJECT (ajout_employe, spinbutton_jouremploye, "spinbutton_jouremploye");
  GLADE_HOOKUP_OBJECT (ajout_employe, spinbutton_moisemploye, "spinbutton_moisemploye");
  GLADE_HOOKUP_OBJECT (ajout_employe, spinbutton_anneeemploye, "spinbutton_anneeemploye");
  GLADE_HOOKUP_OBJECT (ajout_employe, entryadresseemploye, "entryadresseemploye");
  GLADE_HOOKUP_OBJECT (ajout_employe, spinbutton_jourajoutemploye, "spinbutton_jourajoutemploye");
  GLADE_HOOKUP_OBJECT (ajout_employe, spinbutton_moisajoutemploye, "spinbutton_moisajoutemploye");
  GLADE_HOOKUP_OBJECT (ajout_employe, spinbutton_anneeajoutemploye, "spinbutton_anneeajoutemploye");
  GLADE_HOOKUP_OBJECT (ajout_employe, entrysalaireactuelemploye, "entrysalaireactuelemploye");
  GLADE_HOOKUP_OBJECT (ajout_employe, buttonajouteremploye, "buttonajouteremploye");
  GLADE_HOOKUP_OBJECT (ajout_employe, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (ajout_employe, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (ajout_employe, image17, "image17");
  GLADE_HOOKUP_OBJECT (ajout_employe, label41, "label41");
  GLADE_HOOKUP_OBJECT (ajout_employe, buttonprecedentajouterafficheremploye, "buttonprecedentajouterafficheremploye");
  GLADE_HOOKUP_OBJECT (ajout_employe, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (ajout_employe, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (ajout_employe, image18, "image18");
  GLADE_HOOKUP_OBJECT (ajout_employe, label42, "label42");
  GLADE_HOOKUP_OBJECT (ajout_employe, comboboxspecialite, "comboboxspecialite");
  GLADE_HOOKUP_OBJECT (ajout_employe, comboboxsituation, "comboboxsituation");
  GLADE_HOOKUP_OBJECT (ajout_employe, comboboxsexe, "comboboxsexe");
  GLADE_HOOKUP_OBJECT (ajout_employe, labelnom, "labelnom");
  GLADE_HOOKUP_OBJECT (ajout_employe, labelprenom, "labelprenom");
  GLADE_HOOKUP_OBJECT (ajout_employe, labeldatenaissance, "labeldatenaissance");
  GLADE_HOOKUP_OBJECT (ajout_employe, labelsexe, "labelsexe");
  GLADE_HOOKUP_OBJECT (ajout_employe, labelciN, "labelciN");
  GLADE_HOOKUP_OBJECT (ajout_employe, labeladresse, "labeladresse");
  GLADE_HOOKUP_OBJECT (ajout_employe, labelsituationfamiliale, "labelsituationfamiliale");
  GLADE_HOOKUP_OBJECT (ajout_employe, labeldateembauche, "labeldateembauche");
  GLADE_HOOKUP_OBJECT (ajout_employe, labelsalaireactuel, "labelsalaireactuel");
  GLADE_HOOKUP_OBJECT (ajout_employe, labelspecialite, "labelspecialite");

  return ajout_employe;
}

GtkWidget*
create_Afficher_employe (void)
{
  GtkWidget *Afficher_employe;
  GtkWidget *fixed7;
  GtkWidget *entryide;
  GtkWidget *entrynome;
  GtkWidget *buttonrechercheafficheremploye;
  GtkWidget *image19;
  GtkWidget *labelidemploye;
  GtkWidget *labelnomemploye;
  GtkWidget *buttonsupprimerafficheremploye;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image22;
  GtkWidget *label47;
  GtkWidget *buttonmodifierafficheremploye;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image21;
  GtkWidget *label46;
  GtkWidget *buttonajouterafficheremploye;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image20;
  GtkWidget *label45;
  GtkWidget *buttonprecedentaffichergestionemploye;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image23;
  GtkWidget *label48;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview_employe;

  Afficher_employe = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Afficher_employe, 800, 500);
  gtk_window_set_title (GTK_WINDOW (Afficher_employe), _("afficher employ\303\251"));
  gtk_window_set_position (GTK_WINDOW (Afficher_employe), GTK_WIN_POS_CENTER);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (Afficher_employe), fixed7);
  gtk_widget_set_size_request (fixed7, 800, 500);

  entryide = gtk_entry_new ();
  gtk_widget_show (entryide);
  gtk_fixed_put (GTK_FIXED (fixed7), entryide, 128, 32);
  gtk_widget_set_size_request (entryide, 112, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryide), 8226);

  entrynome = gtk_entry_new ();
  gtk_widget_show (entrynome);
  gtk_fixed_put (GTK_FIXED (fixed7), entrynome, 336, 32);
  gtk_widget_set_size_request (entrynome, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynome), 8226);

  buttonrechercheafficheremploye = gtk_button_new ();
  gtk_widget_show (buttonrechercheafficheremploye);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonrechercheafficheremploye, 512, 32);
  gtk_widget_set_size_request (buttonrechercheafficheremploye, 48, 29);

  image19 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_container_add (GTK_CONTAINER (buttonrechercheafficheremploye), image19);

  labelidemploye = gtk_label_new (_("<span foreground=\"BLACK\"><b> ID :</b> </span>"));
  gtk_widget_show (labelidemploye);
  gtk_fixed_put (GTK_FIXED (fixed7), labelidemploye, 64, 40);
  gtk_widget_set_size_request (labelidemploye, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelidemploye), TRUE);

  labelnomemploye = gtk_label_new (_("<span foreground=\"BLACK\"><b> NOM :</b> </span>"));
  gtk_widget_show (labelnomemploye);
  gtk_fixed_put (GTK_FIXED (fixed7), labelnomemploye, 272, 40);
  gtk_widget_set_size_request (labelnomemploye, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelnomemploye), TRUE);

  buttonsupprimerafficheremploye = gtk_button_new ();
  gtk_widget_show (buttonsupprimerafficheremploye);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonsupprimerafficheremploye, 592, 432);
  gtk_widget_set_size_request (buttonsupprimerafficheremploye, 120, 37);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (buttonsupprimerafficheremploye), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image22 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox16), image22, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox16), label47, FALSE, FALSE, 0);

  buttonmodifierafficheremploye = gtk_button_new ();
  gtk_widget_show (buttonmodifierafficheremploye);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonmodifierafficheremploye, 432, 432);
  gtk_widget_set_size_request (buttonmodifierafficheremploye, 112, 37);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (buttonmodifierafficheremploye), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image21 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox15), image21, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox15), label46, FALSE, FALSE, 0);

  buttonajouterafficheremploye = gtk_button_new ();
  gtk_widget_show (buttonajouterafficheremploye);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonajouterafficheremploye, 248, 432);
  gtk_widget_set_size_request (buttonajouterafficheremploye, 120, 40);
  gtk_container_set_border_width (GTK_CONTAINER (buttonajouterafficheremploye), 3);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (buttonajouterafficheremploye), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image20 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox14), image20, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox14), label45, FALSE, FALSE, 0);

  buttonprecedentaffichergestionemploye = gtk_button_new ();
  gtk_widget_show (buttonprecedentaffichergestionemploye);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonprecedentaffichergestionemploye, 80, 432);
  gtk_widget_set_size_request (buttonprecedentaffichergestionemploye, 98, 37);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (buttonprecedentaffichergestionemploye), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image23 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox17), image23, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Pr\303\251c\303\251dent "));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox17), label48, FALSE, FALSE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed7), scrolledwindow2, 32, 88);
  gtk_widget_set_size_request (scrolledwindow2, 736, 328);

  treeview_employe = gtk_tree_view_new ();
  gtk_widget_show (treeview_employe);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview_employe);
  gtk_widget_set_size_request (treeview_employe, 736, 328);

  g_signal_connect ((gpointer) buttonrechercheafficheremploye, "clicked",
                    G_CALLBACK (on_buttonrechercheafficheremploye_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsupprimerafficheremploye, "clicked",
                    G_CALLBACK (on_buttonsupprimerafficheremploye_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifierafficheremploye, "clicked",
                    G_CALLBACK (on_buttonmodifierafficheremploye_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonajouterafficheremploye, "clicked",
                    G_CALLBACK (on_buttonajouterafficheremploye_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonprecedentaffichergestionemploye, "clicked",
                    G_CALLBACK (on_buttonprecedentaffichergestionemploye_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Afficher_employe, Afficher_employe, "Afficher_employe");
  GLADE_HOOKUP_OBJECT (Afficher_employe, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Afficher_employe, entryide, "entryide");
  GLADE_HOOKUP_OBJECT (Afficher_employe, entrynome, "entrynome");
  GLADE_HOOKUP_OBJECT (Afficher_employe, buttonrechercheafficheremploye, "buttonrechercheafficheremploye");
  GLADE_HOOKUP_OBJECT (Afficher_employe, image19, "image19");
  GLADE_HOOKUP_OBJECT (Afficher_employe, labelidemploye, "labelidemploye");
  GLADE_HOOKUP_OBJECT (Afficher_employe, labelnomemploye, "labelnomemploye");
  GLADE_HOOKUP_OBJECT (Afficher_employe, buttonsupprimerafficheremploye, "buttonsupprimerafficheremploye");
  GLADE_HOOKUP_OBJECT (Afficher_employe, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Afficher_employe, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Afficher_employe, image22, "image22");
  GLADE_HOOKUP_OBJECT (Afficher_employe, label47, "label47");
  GLADE_HOOKUP_OBJECT (Afficher_employe, buttonmodifierafficheremploye, "buttonmodifierafficheremploye");
  GLADE_HOOKUP_OBJECT (Afficher_employe, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Afficher_employe, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Afficher_employe, image21, "image21");
  GLADE_HOOKUP_OBJECT (Afficher_employe, label46, "label46");
  GLADE_HOOKUP_OBJECT (Afficher_employe, buttonajouterafficheremploye, "buttonajouterafficheremploye");
  GLADE_HOOKUP_OBJECT (Afficher_employe, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Afficher_employe, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Afficher_employe, image20, "image20");
  GLADE_HOOKUP_OBJECT (Afficher_employe, label45, "label45");
  GLADE_HOOKUP_OBJECT (Afficher_employe, buttonprecedentaffichergestionemploye, "buttonprecedentaffichergestionemploye");
  GLADE_HOOKUP_OBJECT (Afficher_employe, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Afficher_employe, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Afficher_employe, image23, "image23");
  GLADE_HOOKUP_OBJECT (Afficher_employe, label48, "label48");
  GLADE_HOOKUP_OBJECT (Afficher_employe, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (Afficher_employe, treeview_employe, "treeview_employe");

  return Afficher_employe;
}

GtkWidget*
create_accueil (void)
{
  GtkWidget *accueil;
  GtkWidget *fixed8;
  GtkWidget *image32;
  GtkWidget *buttonacceuilespaceemploye;
  GtkWidget *buttonaccueilespaceadmin;
  GtkWidget *labelsmartfarm;

  accueil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (accueil, 640, 424);
  gtk_window_set_title (GTK_WINDOW (accueil), _("Accueil "));
  gtk_window_set_position (GTK_WINDOW (accueil), GTK_WIN_POS_CENTER);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (accueil), fixed8);
  gtk_widget_set_size_request (fixed8, 640, 424);

  image32 = create_pixmap (accueil, "smartfarm.png");
  gtk_widget_show (image32);
  gtk_fixed_put (GTK_FIXED (fixed8), image32, 0, 0);
  gtk_widget_set_size_request (image32, 640, 424);

  buttonacceuilespaceemploye = gtk_button_new_with_mnemonic (_("Menu employe "));
  gtk_widget_show (buttonacceuilespaceemploye);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonacceuilespaceemploye, 272, 288);
  gtk_widget_set_size_request (buttonacceuilespaceemploye, 304, 72);

  buttonaccueilespaceadmin = gtk_button_new_with_mnemonic (_("Menu administrateur"));
  gtk_widget_show (buttonaccueilespaceadmin);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonaccueilespaceadmin, 272, 192);
  gtk_widget_set_size_request (buttonaccueilespaceadmin, 304, 69);

  labelsmartfarm = gtk_label_new (_("<span foreground=\"blue\"><b> BIENVENUE CHEZ SMART-FARM </b> </span>"));
  gtk_widget_show (labelsmartfarm);
  gtk_fixed_put (GTK_FIXED (fixed8), labelsmartfarm, 144, 16);
  gtk_widget_set_size_request (labelsmartfarm, 376, 80);
  gtk_label_set_use_markup (GTK_LABEL (labelsmartfarm), TRUE);

  g_signal_connect ((gpointer) buttonacceuilespaceemploye, "clicked",
                    G_CALLBACK (on_buttonacceuilespaceemploye_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonaccueilespaceadmin, "clicked",
                    G_CALLBACK (on_buttonaccueilespaceadmin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (accueil, accueil, "accueil");
  GLADE_HOOKUP_OBJECT (accueil, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (accueil, image32, "image32");
  GLADE_HOOKUP_OBJECT (accueil, buttonacceuilespaceemploye, "buttonacceuilespaceemploye");
  GLADE_HOOKUP_OBJECT (accueil, buttonaccueilespaceadmin, "buttonaccueilespaceadmin");
  GLADE_HOOKUP_OBJECT (accueil, labelsmartfarm, "labelsmartfarm");

  return accueil;
}

GtkWidget*
create_admin (void)
{
  GtkWidget *admin;
  GtkWidget *fixed9;
  GtkWidget *image35;
  GtkWidget *buttonadminafficheremploye;
  GtkWidget *buttonprecedentadminaccueil;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image28;
  GtkWidget *label50;
  GtkWidget *labeladmin;
  GtkWidget *buttoncamera;

  admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (admin, 696, 536);
  gtk_window_set_title (GTK_WINDOW (admin), _("Admin"));
  gtk_window_set_position (GTK_WINDOW (admin), GTK_WIN_POS_CENTER);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (admin), fixed9);
  gtk_widget_set_size_request (fixed9, 696, 536);

  image35 = create_pixmap (admin, "visiteurimage.jpeg");
  gtk_widget_show (image35);
  gtk_fixed_put (GTK_FIXED (fixed9), image35, 0, 0);
  gtk_widget_set_size_request (image35, 712, 536);

  buttonadminafficheremploye = gtk_button_new_with_mnemonic (_("gestion des employes"));
  gtk_widget_show (buttonadminafficheremploye);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonadminafficheremploye, 224, 160);
  gtk_widget_set_size_request (buttonadminafficheremploye, 304, 64);

  buttonprecedentadminaccueil = gtk_button_new ();
  gtk_widget_show (buttonprecedentadminaccueil);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonprecedentadminaccueil, 48, 456);
  gtk_widget_set_size_request (buttonprecedentadminaccueil, 136, 45);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonprecedentadminaccueil), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image28 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox18), image28, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Pr\303\251c\303\251dent "));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox18), label50, FALSE, FALSE, 0);

  labeladmin = gtk_label_new (_("<span foreground=\"WHITE\"><b>BIENVENUE MONSIEUR L'ADMIN</b> </span>"));
  gtk_widget_show (labeladmin);
  gtk_fixed_put (GTK_FIXED (fixed9), labeladmin, 152, 16);
  gtk_widget_set_size_request (labeladmin, 424, 73);
  gtk_label_set_use_markup (GTK_LABEL (labeladmin), TRUE);

  buttoncamera = gtk_button_new_with_mnemonic (_("Camera de surveillance "));
  gtk_widget_show (buttoncamera);
  gtk_fixed_put (GTK_FIXED (fixed9), buttoncamera, 224, 280);
  gtk_widget_set_size_request (buttoncamera, 304, 64);

  g_signal_connect ((gpointer) buttonadminafficheremploye, "clicked",
                    G_CALLBACK (on_buttonadminafficheremploye_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonprecedentadminaccueil, "clicked",
                    G_CALLBACK (on_buttonprecedentadminaccueil_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttoncamera, "clicked",
                    G_CALLBACK (on_buttoncamera_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (admin, admin, "admin");
  GLADE_HOOKUP_OBJECT (admin, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (admin, image35, "image35");
  GLADE_HOOKUP_OBJECT (admin, buttonadminafficheremploye, "buttonadminafficheremploye");
  GLADE_HOOKUP_OBJECT (admin, buttonprecedentadminaccueil, "buttonprecedentadminaccueil");
  GLADE_HOOKUP_OBJECT (admin, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (admin, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (admin, image28, "image28");
  GLADE_HOOKUP_OBJECT (admin, label50, "label50");
  GLADE_HOOKUP_OBJECT (admin, labeladmin, "labeladmin");
  GLADE_HOOKUP_OBJECT (admin, buttoncamera, "buttoncamera");

  return admin;
}

GtkWidget*
create_modifier_employe (void)
{
  GtkWidget *modifier_employe;
  GtkWidget *fixed10;
  GtkWidget *entrynome;
  GtkWidget *entryprenome;
  GtkWidget *entrycin;
  GtkWidget *entryadresse;
  GtkWidget *entrysalaireactuel;
  GtkWidget *comboboxsituationn;
  GtkWidget *comboboxsexee;
  GtkWidget *comboboxspecialitee;
  GtkWidget *buttonmodifieremploye;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image30;
  GtkWidget *label66;
  GtkWidget *buttonprecedentmodifierafficheremploye;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image31;
  GtkWidget *label67;
  GtkWidget *labelide;
  GtkWidget *labelnome;
  GtkWidget *labelprenome;
  GtkWidget *labelsexe;
  GtkWidget *labeldatenaissance;
  GtkWidget *labelcin;
  GtkWidget *labelsituation;
  GtkWidget *labeladresse;
  GtkWidget *labeldateembauche;
  GtkWidget *label63;
  GtkWidget *label64;
  GtkWidget *label65;
  GtkWidget *labelspecialite;
  GtkWidget *labelsalaireactuel;

  modifier_employe = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modifier_employe, 700, 600);
  gtk_window_set_title (GTK_WINDOW (modifier_employe), _("modifier employe"));
  gtk_window_set_position (GTK_WINDOW (modifier_employe), GTK_WIN_POS_CENTER);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (modifier_employe), fixed10);
  gtk_widget_set_size_request (fixed10, 700, 600);

  entrynome = gtk_entry_new ();
  gtk_widget_show (entrynome);
  gtk_fixed_put (GTK_FIXED (fixed10), entrynome, 240, 72);
  gtk_widget_set_size_request (entrynome, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynome), 8226);

  entryprenome = gtk_entry_new ();
  gtk_widget_show (entryprenome);
  gtk_fixed_put (GTK_FIXED (fixed10), entryprenome, 240, 128);
  gtk_widget_set_size_request (entryprenome, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenome), 8226);

  entrycin = gtk_entry_new ();
  gtk_widget_show (entrycin);
  gtk_fixed_put (GTK_FIXED (fixed10), entrycin, 232, 264);
  gtk_widget_set_size_request (entrycin, 176, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycin), 8226);

  entryadresse = gtk_entry_new ();
  gtk_widget_show (entryadresse);
  gtk_fixed_put (GTK_FIXED (fixed10), entryadresse, 232, 368);
  gtk_widget_set_size_request (entryadresse, 176, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryadresse), 8226);

  entrysalaireactuel = gtk_entry_new ();
  gtk_widget_show (entrysalaireactuel);
  gtk_fixed_put (GTK_FIXED (fixed10), entrysalaireactuel, 232, 464);
  gtk_widget_set_size_request (entrysalaireactuel, 176, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrysalaireactuel), 8226);

  comboboxsituationn = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxsituationn);
  gtk_fixed_put (GTK_FIXED (fixed10), comboboxsituationn, 224, 320);
  gtk_widget_set_size_request (comboboxsituationn, 192, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxsituationn), _("mari\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxsituationn), _("c\303\251libataire"));

  comboboxsexee = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxsexee);
  gtk_fixed_put (GTK_FIXED (fixed10), comboboxsexee, 232, 176);
  gtk_widget_set_size_request (comboboxsexee, 184, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxsexee), _("male "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxsexee), _("female"));

  comboboxspecialitee = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxspecialitee);
  gtk_fixed_put (GTK_FIXED (fixed10), comboboxspecialitee, 232, 512);
  gtk_widget_set_size_request (comboboxspecialitee, 184, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxspecialitee), _("ing\303\251nieur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxspecialitee), _("v\303\251t\303\251rinaire"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxspecialitee), _("\303\251lectricien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxspecialitee), _("agriculteur "));

  buttonmodifieremploye = gtk_button_new ();
  gtk_widget_show (buttonmodifieremploye);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonmodifieremploye, 464, 552);
  gtk_widget_set_size_request (buttonmodifieremploye, 130, 37);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (buttonmodifieremploye), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image30 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox20), image30, FALSE, FALSE, 0);

  label66 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox20), label66, FALSE, FALSE, 0);

  buttonprecedentmodifierafficheremploye = gtk_button_new ();
  gtk_widget_show (buttonprecedentmodifierafficheremploye);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonprecedentmodifierafficheremploye, 40, 560);
  gtk_widget_set_size_request (buttonprecedentmodifierafficheremploye, 120, 37);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (buttonprecedentmodifierafficheremploye), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image31 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox21), image31, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("Pr\303\251c\303\251dent "));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox21), label67, FALSE, FALSE, 0);

  labelide = gtk_label_new (_("<span foreground=\"BLACK\"><b>ID :</b> </span>"));
  gtk_widget_show (labelide);
  gtk_fixed_put (GTK_FIXED (fixed10), labelide, 128, 32);
  gtk_widget_set_size_request (labelide, 80, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelide), TRUE);

  labelnome = gtk_label_new (_("<span foreground=\"BLACK\"><b>NOM :</b> </span>"));
  gtk_widget_show (labelnome);
  gtk_fixed_put (GTK_FIXED (fixed10), labelnome, 136, 80);
  gtk_widget_set_size_request (labelnome, 64, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelnome), TRUE);

  labelprenome = gtk_label_new (_("<span foreground=\"BLACK\"><b>PR\303\211NOM :</b> </span>"));
  gtk_widget_show (labelprenome);
  gtk_fixed_put (GTK_FIXED (fixed10), labelprenome, 136, 128);
  gtk_widget_set_size_request (labelprenome, 72, 32);
  gtk_label_set_use_markup (GTK_LABEL (labelprenome), TRUE);

  labelsexe = gtk_label_new (_("<span foreground=\"BLACK\"><b>SEXE :</b> </span>"));
  gtk_widget_show (labelsexe);
  gtk_fixed_put (GTK_FIXED (fixed10), labelsexe, 144, 184);
  gtk_widget_set_size_request (labelsexe, 56, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelsexe), TRUE);

  labeldatenaissance = gtk_label_new (_("<span foreground=\"BLACK\"><b>DATE DE NAISSANCE :</b> </span>"));
  gtk_widget_show (labeldatenaissance);
  gtk_fixed_put (GTK_FIXED (fixed10), labeldatenaissance, 72, 224);
  gtk_widget_set_size_request (labeldatenaissance, 161, 32);
  gtk_label_set_use_markup (GTK_LABEL (labeldatenaissance), TRUE);

  labelcin = gtk_label_new (_("<span foreground=\"BLACK\"><b>C.I.N :</b> </span>"));
  gtk_widget_show (labelcin);
  gtk_fixed_put (GTK_FIXED (fixed10), labelcin, 144, 280);
  gtk_widget_set_size_request (labelcin, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelcin), TRUE);

  labelsituation = gtk_label_new (_("<span foreground=\"BLACK\"><b>SITUATION FAMILIALE :</b> </span>"));
  gtk_widget_show (labelsituation);
  gtk_fixed_put (GTK_FIXED (fixed10), labelsituation, 40, 320);
  gtk_widget_set_size_request (labelsituation, 185, 32);
  gtk_label_set_use_markup (GTK_LABEL (labelsituation), TRUE);

  labeladresse = gtk_label_new (_("<span foreground=\"BLACK\"><b>ADRESSE:</b> </span>"));
  gtk_widget_show (labeladresse);
  gtk_fixed_put (GTK_FIXED (fixed10), labeladresse, 104, 376);
  gtk_widget_set_size_request (labeladresse, 97, 25);
  gtk_label_set_use_markup (GTK_LABEL (labeladresse), TRUE);

  labeldateembauche = gtk_label_new (_("<span foreground=\"BLACK\"><b>DATE D'EMBAUCHE :</b> </span>"));
  gtk_widget_show (labeldateembauche);
  gtk_fixed_put (GTK_FIXED (fixed10), labeldateembauche, 56, 424);
  gtk_widget_set_size_request (labeldateembauche, 168, 32);
  gtk_label_set_use_markup (GTK_LABEL (labeldateembauche), TRUE);

  label63 = gtk_label_new (_("<span foreground=\"BLACK\"><b>label63 </b> </span>"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed10), label63, 288, 32);
  gtk_widget_set_size_request (label63, 96, 17);
  gtk_label_set_use_markup (GTK_LABEL (label63), TRUE);

  label64 = gtk_label_new (_("<span foreground=\"BLACK\"><b>label64</b> </span>"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed10), label64, 240, 224);
  gtk_widget_set_size_request (label64, 136, 25);
  gtk_label_set_use_markup (GTK_LABEL (label64), TRUE);

  label65 = gtk_label_new (_("<span foreground=\"BLACK\"><b>label65</b> </span>"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed10), label65, 248, 424);
  gtk_widget_set_size_request (label65, 144, 25);
  gtk_label_set_use_markup (GTK_LABEL (label65), TRUE);

  labelspecialite = gtk_label_new (_("<span foreground=\"BLACK\"><b>SPECIALIT\303\211 :</b> </span>"));
  gtk_widget_show (labelspecialite);
  gtk_fixed_put (GTK_FIXED (fixed10), labelspecialite, 72, 520);
  gtk_widget_set_size_request (labelspecialite, 145, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelspecialite), TRUE);

  labelsalaireactuel = gtk_label_new (_("<span foreground=\"BLACK\"><b>SALAIRE ACTUEL :</b> </span>"));
  gtk_widget_show (labelsalaireactuel);
  gtk_fixed_put (GTK_FIXED (fixed10), labelsalaireactuel, 72, 464);
  gtk_widget_set_size_request (labelsalaireactuel, 153, 33);
  gtk_label_set_use_markup (GTK_LABEL (labelsalaireactuel), TRUE);

  g_signal_connect ((gpointer) buttonmodifieremploye, "clicked",
                    G_CALLBACK (on_buttonmodifieremploye_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonprecedentmodifierafficheremploye, "clicked",
                    G_CALLBACK (on_buttonprecedentmodifierafficheremploye_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_employe, modifier_employe, "modifier_employe");
  GLADE_HOOKUP_OBJECT (modifier_employe, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (modifier_employe, entrynome, "entrynome");
  GLADE_HOOKUP_OBJECT (modifier_employe, entryprenome, "entryprenome");
  GLADE_HOOKUP_OBJECT (modifier_employe, entrycin, "entrycin");
  GLADE_HOOKUP_OBJECT (modifier_employe, entryadresse, "entryadresse");
  GLADE_HOOKUP_OBJECT (modifier_employe, entrysalaireactuel, "entrysalaireactuel");
  GLADE_HOOKUP_OBJECT (modifier_employe, comboboxsituationn, "comboboxsituationn");
  GLADE_HOOKUP_OBJECT (modifier_employe, comboboxsexee, "comboboxsexee");
  GLADE_HOOKUP_OBJECT (modifier_employe, comboboxspecialitee, "comboboxspecialitee");
  GLADE_HOOKUP_OBJECT (modifier_employe, buttonmodifieremploye, "buttonmodifieremploye");
  GLADE_HOOKUP_OBJECT (modifier_employe, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (modifier_employe, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (modifier_employe, image30, "image30");
  GLADE_HOOKUP_OBJECT (modifier_employe, label66, "label66");
  GLADE_HOOKUP_OBJECT (modifier_employe, buttonprecedentmodifierafficheremploye, "buttonprecedentmodifierafficheremploye");
  GLADE_HOOKUP_OBJECT (modifier_employe, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (modifier_employe, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (modifier_employe, image31, "image31");
  GLADE_HOOKUP_OBJECT (modifier_employe, label67, "label67");
  GLADE_HOOKUP_OBJECT (modifier_employe, labelide, "labelide");
  GLADE_HOOKUP_OBJECT (modifier_employe, labelnome, "labelnome");
  GLADE_HOOKUP_OBJECT (modifier_employe, labelprenome, "labelprenome");
  GLADE_HOOKUP_OBJECT (modifier_employe, labelsexe, "labelsexe");
  GLADE_HOOKUP_OBJECT (modifier_employe, labeldatenaissance, "labeldatenaissance");
  GLADE_HOOKUP_OBJECT (modifier_employe, labelcin, "labelcin");
  GLADE_HOOKUP_OBJECT (modifier_employe, labelsituation, "labelsituation");
  GLADE_HOOKUP_OBJECT (modifier_employe, labeladresse, "labeladresse");
  GLADE_HOOKUP_OBJECT (modifier_employe, labeldateembauche, "labeldateembauche");
  GLADE_HOOKUP_OBJECT (modifier_employe, label63, "label63");
  GLADE_HOOKUP_OBJECT (modifier_employe, label64, "label64");
  GLADE_HOOKUP_OBJECT (modifier_employe, label65, "label65");
  GLADE_HOOKUP_OBJECT (modifier_employe, labelspecialite, "labelspecialite");
  GLADE_HOOKUP_OBJECT (modifier_employe, labelsalaireactuel, "labelsalaireactuel");

  return modifier_employe;
}

